server:
  port: 8086

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: validate
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/queue-system-example-facility
  username: -----
  password: -----

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: example-facility
    password: Facility123
    virtual-host: queue-system

custom:
  configuration:
    queue-name: test123
    facilityId: 1
